package com.project.student_manager.enums;

public enum ErrorType {
    STUDENT_ALREADY_REGISTERED,
    COURSE_ALREADY_REGISTERED,
    STUDENT_NOT_FOUND,
    COURSE_NOT_FOUND,
    NOT_ELIGIBLE,
    ENROLLMENT_NOT_FOUND,
    ENROLLMENT_ALREADY_EXISTS
}
